### ISSUE TITLE
Readme requires par_init object to run

### ISSUE THREAD

**Issue by jameshay218** [chrism0dwk/wuhan#1]
Cannot currently run the readme without manually specifying par_init. Suggest including this and set.seed

**Comment by chrism0dwk** [comment]
Fixed in #fa1bbf7.  Thanks for noticing James!  I haven't supplied a set.seed because the original bootstrap calculations were performed on a computing cluster with many parallel jobs requiring different seeds.  In principle this might be repeatable on arbitrary clusters, but didn't seem feasible.  The main point is that in the limit, Monte Carlo simulations should converge to the same sampling distributions no matter what the starting seed.
